// Copyright 2021-2022, University of Colorado Boulder

/**
 * Generates the tsconfig.json file for typescript compilation.
 *
 * See https://github.com/phetsims/chipper/issues/63
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */

// modules
const fixEOL = require( './fixEOL' );
const writeFileAndGitAdd = require( '../../../perennial-alias/js/common/writeFileAndGitAdd' );

/**
 * @param {string} repo
 *
 * @returns {Promise}
 */
module.exports = async function( repo ) {

  const phetioWrappers = repo === 'phet-io-wrappers' ? `,
    "common/js/**/*"` : '';

  const string = `// This file was automatically generated by grunt update
{
  "extends": "../chipper/tsconfig-core.json",
  "include": [
    "js/**/*",
    "images/**/*",
    "mipmaps/**/*",
    "sounds/**/*"${phetioWrappers}
  ]
}`;

  await writeFileAndGitAdd( repo, 'tsconfig.json', fixEOL( string ) );
};