// Copyright 2025, University of Colorado Boulder

/**
 * FluentConstant is the type generated by generateFluentTypes for the entries in a SimFluent.ts file that require no inputs
 * for a pattern (i.e., constants that are interpolated using the fluent bundle but have no parameters).
 *
 * @author Sam Reid (PhET Interactive Simulations)
 * @author Jesse Greenberg (PhET Interactive Simulations)
 */

import { DerivedProperty1 } from '../../../axon/js/DerivedProperty.js';
import ReadOnlyProperty from '../../../axon/js/ReadOnlyProperty.js';
import { FluentBundle } from '../../../chipper/js/browser-and-node/FluentLibrary.js';
import affirm from '../../../perennial-alias/js/browser-and-node/affirm.js';
import chipper from './chipper.js';

export default class FluentConstant extends DerivedProperty1<string, FluentBundle> {

  /**
   * Creates a string Property that will update when the bundle changes.
   *
   * @param bundleProperty
   * @param key - The string key, where nesting is indicated by underscores (since that is compatible with Fluent syntax)
   *              such as a11y_summary_playAreaSummaryIntro
   */
  public constructor( bundleProperty: ReadOnlyProperty<FluentBundle>, key: string ) {

    super( [ bundleProperty ], bundle => {
      const message = bundle.getMessage( key );

      const errors: Array<Error> = [];

      affirm( message, `Fluent message not found for key: ${key}` );
      affirm( message.value, `Fluent message value not found for key: ${key}` );
      const result = bundle.formatPattern( message.value, {}, errors );

      assert && assert( errors.length === 0, `Fluent errors found when formatting message: ${errors}` );
      return result;
    } );
  }
}

chipper.register( 'FluentConstant', FluentConstant );